services:
  database:
    image: 'postgres:alpine'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: beep
      POSTGRES_PASSWORD: beep
      POSTGRES_DB: beep_auth
  valkey:
    image: docker.io/bitnami/valkey:8.1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'valkey-data:/bitnami/valkey/data'
  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - 'mailpit-data:/data'
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db-data:
  mailpit-data:
  valkey-data:
