# this is nowhere near production ready lol AND only for nest. not tested elsewhere
services:
  server:
    image: ghcr.io/moonbeeper/beepauth-server:nightly
    restart: unless-stopped
    depends_on:
      - valkey
    volumes:
      - ./config.toml:/app/config.toml:ro
      - /var/run/postgresql:/var/run/postgresql # unix socket
    ports:
      - ${AVAILABLE_PORT}:8080

  valkey:
    image: docker.io/bitnami/valkey:8.1
    environment:
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - VALKEY_PASSWORD_FILE=/run/secrets/valkey-password
    volumes:
      - 'valkey-data:/bitnami/valkey/data'

  # the frontend will be directly build on nest and served from caddy
volumes:
  db-data:
  valkey-data:

secrets:
  valkey-password:
    file: ./valkey_pwd.txt