/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login via user login or email and password
         * @description Simple login with password. If the user has TOTP enabled, you'll get a TOTP challenge instead of a session.
         */
        post: operations["authPasswordLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start the OAuth authorization request
         * @description Starts the OAuth authorization by first validating the request and then appending a temporary cookie with the
         *     necessary information to continue the process. If the user has already authorized the app with the requested scopes,
         *     it will skip the consent prompt and redirect the user to the client's callback with the code directly.
         */
        get: operations["authorize"];
        put?: never;
        /**
         * Finish a OAuth authorization request
         * @description Finish the OAuth authorization request by approving or denying it. If approved, the user will be redirected to the
         *     client's callback. This consumes the authorization flow, so it cannot be used again.
         */
        post: operations["finish_authorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/oauth/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get information about the current OAuth authorization request
         * @description Its used to get the info about the app and requested scopes before approving or denying the request without
         *     consuming the authorization flow. To be able to use it, the user must have a previously started the authorization
         *     flow.
         *
         *     If the request has new scopes that the user has not approved yet, they won't be added until the oauth client has
         *     exchanged the code response for a access token. That also means that the user's authorized app won't be updated.
         */
        get: operations["get_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a OAuth code for a access token
         * @description Exchanges a previously obtained OAuth code for an access token to be used in future requests. The token will be
         *     valid until the user revokes the authorization or the OAuth app is deleted. The code will be consumed after
         *     the first pass of validation, after the second pass (code challenge, etc) it will be consumed and you will need to
         *     restart the authorization process from the beginning.
         */
        post: operations["authOauthToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange the OTP code sent to the user's email to finish a flow */
        post: operations["authOtpExchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/exchange-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange the code sent to the user's email for a session */
        post: operations["authOtpExchangeLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login or register
         * @description This will send a code to the provided email address to either login or register
         */
        post: operations["authOtpLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the password reset flow
         * @description This will send a password reset link to the user's email to begin the password reset flow
         */
        post: operations["reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current status of the password reset flow.
         * @description This endpoint is just used for checking if the password reset flow requires TOTP verification or not to continue.
         */
        get: operations["reset_password_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset/{id}/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the new password for the user
         * @description If the user has TOTP enabled, you'll need to run through the TOTP flow first or else the flow will be deleted.
         */
        put: operations["reset_password_set"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify the TOTP code or recovery code to continue the password reset flow.
         * @description If the user doesn't have TOTP enabled, it will just return OK lol
         */
        post: operations["reset_password_check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out of this current session */
        post: operations["signout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the TOTP enable flow */
        post: operations["enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/enable/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize enabling TOTP for the current user */
        post: operations["enable_exchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a Link ID to finalize a Sudo enable TOTP flow */
        post: operations["exchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/exchange-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a Link ID to finalize a TOTP login request */
        post: operations["exchange_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * teapot endpoint
         * @description haha funny teapot woooo
         */
        get: operations["funny"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user created OAuth apps */
        get: operations["list_apps"];
        put?: never;
        /** Create a new OAuth app */
        post: operations["create_app"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get info about an OAuth app you created */
        get: operations["get_app"];
        /** Update an OAuth app */
        put: operations["update_app"];
        post?: never;
        /** Delete an OAuth app by its ID */
        delete: operations["delete_app"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/authorized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user authorized OAuth apps */
        get: operations["list_authorized"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/authorized/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get info about an authorized OAuth app */
        get: operations["get_authorized"];
        put?: never;
        post?: never;
        /** Delete an authorized OAuth app */
        delete: operations["remove_authorized"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current session */
        get: operations["current_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete all your open sessions */
        delete: operations["delete_all_sessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all your open sessions */
        get: operations["list_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get info about one of your open sessions */
        get: operations["get_session"];
        put?: never;
        post?: never;
        /** Delete one of your sessions */
        delete: operations["delete_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sudo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the options for enabling sudo */
        get: operations["get_sudo_options"];
        put?: never;
        /**
         * Enable sudo for the current session
         * @description This will start the requested flow to enable sudo
         */
        post: operations["enable_sudo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sudo/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the sudo status of the session */
        get: operations["get_sudo_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disable TOTP from this account
         * @description This will disable TOTP from your account IF you have TOTP enabled
         */
        delete: operations["disable"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/totp/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get your TOTP recovery codes
         * @description This will return your TOTP recovery codes IF you have TOTP enabled
         */
        get: operations["get_totp_recovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user info
         * @description Get's the info about the current user that's authenticated via a session or via an oauth2 access token.
         */
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ApiHttpError: "Database" | "InvalidLogin" | "PasswordHashing" | "UserAlreadyExists" | "Unknown" | "UnknownAlt" | "EmailError" | "RedisError" | "SystemTimeError" | "InvalidOTPCode" | "InvalidTOTPCode" | "TOTPIsRequired" | "Teapot" | "TOTPIsAlreadyEnabled" | "YouAreNotLoggedIn" | "InvalidRecoveryCode" | "UsedRecoveryCode" | "TOTPIsNotEnabled" | "OTPRecoveryFlowNotFound" | "TOTPFlowNotFound" | "EmailIsNotVerified" | "EmailIsAlreadyVerified" | "InvalidEmailVerification" | "InvalidAuthentication" | "FailedParsingScopes" | "OAuthAppNotFound" | "OAuthAppNotOwned" | "OAuthAppEmptyScopes" | "OAuthAuthorizationNotFound" | "SudoIsNotEnabled" | "SudoIsAlreadyEnabled" | "SudoCannotBeEnabled" | "TOTPExchangeNotFound" | "OTPExchangeNotFound" | "SessionDoesNotExist" | "FailedParsingURL" | "OAuthInvalidUri" | "PasswordDoesNotMatch" | "PasswordLowStrength" | "RecoveryLinkNotFound" | "ValidationError" | "JsonSyntaxError" | "JsonDataError" | "MissingJsonContentType" | "FailedToBufferContent" | "FailedToDeserializePathParams" | "MissingPathParams" | "FailedToDeserializeQuery" | "EmailVerificationExpired" | "PasswordMatchesOld" | "OauthFlowNotFound" | "FailedToDeserializeForm" | "FailedToDeserializeFormBody" | "MissingFormContentType";
        AuthExchange: {
            /** @description The code that was sent to the email address */
            code: string;
            email: string;
            /** @description The link ID of the OTP flow */
            link_id: components["schemas"]["Ulid"];
        };
        AuthResponse: {
            link_id: components["schemas"]["Ulid"];
        };
        /** @enum {string} */
        CodeChallengeMethod: "S256" | "plain";
        CreateApp: {
            /**
             * @description The callback URL for the OAuth app
             * @example https://oauthdebugger.com/debug
             */
            callback_url: string;
            /**
             * @description The description of the OAuth app
             * @example A description for the oauth app
             */
            description: string;
            /**
             * @description The name of the OAuth app
             * @example My App
             */
            name: string;
            /** @description The scopes the OAuth app can request */
            scopes: string[];
        };
        CreateAppResponse: {
            id: components["schemas"]["StringId"];
            secret_key: string;
        };
        CurrentActiveOptions: {
            otp: boolean;
            totp: boolean;
        };
        EnableExchange: {
            /** @description The TOTP code */
            code: string;
        };
        EnableResponse: {
            recovery_codes: string[];
            secret: string;
        };
        Exchange: {
            /** @description The TOTP code or recovery code */
            code_or_recovery: string;
            /** @description The link ID of the TOTP flow */
            link_id: components["schemas"]["Ulid"];
        };
        ExchangeRequest: {
            /** @description The OAuth app client ID */
            client_id: components["schemas"]["StringId"];
            /** @description The OAuth app client secret */
            client_secret: string;
            /** @description The OAuth code received */
            code: components["schemas"]["StringId"];
            /** @description The origin random string that was used to create the code challenge */
            code_verifier: string;
            /** @description The OAuth grant type, must be `authorization_code` */
            grant_type: components["schemas"]["GrantType"];
            /** @description The redirect url requested when authorizing, must match exactly to the one used when authorizing */
            redirect_uri?: string | null;
        };
        ExchangeResponse: {
            access_token: string;
            scope: string;
            token_type: components["schemas"]["TokenType"];
        };
        FinishAuthorize: {
            /** @description Whether to authorize or deny the request */
            authorize: boolean;
        };
        /** @enum {string} */
        GrantType: "authorization_code";
        HttpError: {
            error: string;
            link_id?: string | null;
            message: string;
        };
        Login: {
            email: string;
        };
        LoginPassword: {
            /** @description May be either the user's login or email */
            login: string;
            password: string;
        };
        OauthApp: {
            callback_url: string;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            id: components["schemas"]["StringId"];
            name: string;
            scopes: string[];
        };
        OauthAuthorized: {
            app: components["schemas"]["StringId"];
            /** Format: date-time */
            created_at: string;
            id: components["schemas"]["Ulid"];
            scopes: string[];
            /** Format: date-time */
            updated_at: string;
            user_id: components["schemas"]["Ulid"];
        };
        OauthHttpError: {
            error: string;
            error_description: string;
            state?: string | null;
        };
        OauthInformation: {
            id: components["schemas"]["StringId"];
            name: string;
            redirect_uri: string;
            scopes: string[];
        };
        /** @enum {string} */
        OauthResponseType: "code" | "token" | "token code" | "code token";
        ResetPassword: {
            email: string;
        };
        ResetPasswordCheck: {
            /** @description The TOTP code or recovery code */
            code_or_recovery: string;
        };
        ResetPasswordExchange: {
            /** @description The new password */
            password: string;
            /** @description The new password again */
            password_confirm: string;
        };
        ResetPasswordStatus: {
            status: components["schemas"]["ResetStatus"];
        };
        /** @enum {string} */
        ResetStatus: "ready" | "needs_totp";
        Session: {
            /** Format: date-time */
            active_expires_at: string;
            browser: string;
            /** Format: date-time */
            created_at: string;
            id: components["schemas"]["Ulid"];
            /** Format: date-time */
            inactive_expires_at: string;
            name: string;
            os: string;
        };
        StringId: string;
        /** @enum {string} */
        SudoEnableOption: "otp" | "totp";
        SudoEnableRequest: {
            /** @description The option to use for enabling sudo */
            option: components["schemas"]["SudoEnableOption"];
        };
        SudoEnableResponse: {
            link_id: components["schemas"]["Ulid"];
            option: components["schemas"]["SudoEnableOption"];
        };
        SudoStatus: {
            enabled: boolean;
        };
        TinySession: {
            /** Format: date-time */
            active_expires_at: string;
            id: components["schemas"]["Ulid"];
            name: string;
            os: string;
        };
        /** @enum {string} */
        TokenType: "bearer" | "mac";
        TotpRecoveryResponse: {
            recovery_codes: string[];
        };
        /** Format: ulid */
        Ulid: string;
        UpdateApp: {
            /**
             * @description The new callback URL for the OAuth app
             * @example https://oauthdebugger.com/debug
             */
            callback_url?: string | null;
            /**
             * @description The new description of the OAuth app
             * @example My new OAuth app description
             */
            description?: string | null;
            /**
             * @description The new name of the OAuth app
             * @example My new OAuth app name
             */
            name?: string | null;
            /** @description The new scopes the OAuth app can request */
            scopes?: string[] | null;
        };
        User: {
            /** Format: date-time */
            created_at: string;
            display_name?: string | null;
            email?: string | null;
            email_verified: boolean;
            id: components["schemas"]["Ulid"];
            login: string;
            totp_enabled: boolean;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authPasswordLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPassword"];
            };
        };
        responses: {
            /** @description Successful login, exchanged for a new session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Bad request (invalid login, email not verified, etc) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description TOTP challenge required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    authorize: {
        parameters: {
            query: {
                /** @description The OAuth response type, must be code! */
                response_type: components["schemas"]["OauthResponseType"];
                /** @description The OAuth client ID */
                client_id: components["schemas"]["StringId"];
                /** @description The redirect after authorization */
                redirect_uri?: string | null;
                /** @description The requested scopes, space separated. If not provided, the OAuth app default scopes will be used */
                scope?: string | null;
                /** @description The state to be returned back after authorization */
                state?: string | null;
                /** @description PKCE code challenge, 43 characters, base64url encoded */
                code_challenge: string;
                /** @description PKCE challenge method, must be S256! */
                code_challenge_method: components["schemas"]["CodeChallengeMethod"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to consent prompt or already authorized (redirected to client) */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OAuth error, validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OauthHttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    finish_authorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishAuthorize"];
            };
        };
        responses: {
            /** @description OAuth authorization approved */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OAuth error, validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated or access denied by the user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    get_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Information about the current OAuth2 authorization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OauthInformation"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description OAuth authorization flow was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    authOauthToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRequest"];
            };
        };
        responses: {
            /** @description OAuth token exchanged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeResponse"];
                };
            };
            /** @description OAuth error, validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    authOtpExchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthExchange"];
            };
        };
        responses: {
            /** @description Successful OTP exchange */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description OTP exchange flow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    authOtpExchangeLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthExchange"];
            };
        };
        responses: {
            /** @description Exchanged for a new session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description TOTP challenge required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    authOtpLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Login flow started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    reset_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPassword"];
            };
        };
        responses: {
            /** @description Started the password reset flow, check your email */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    reset_password_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the reset password flow */
                id: components["schemas"]["Ulid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current status of the reset password flow */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordStatus"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description The reset password flow was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    reset_password_set: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the reset password flow */
                id: components["schemas"]["Ulid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordExchange"];
            };
        };
        responses: {
            /** @description Successfully set the new password */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description The reset password flow was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    reset_password_check: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the reset password flow */
                id: components["schemas"]["Ulid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordCheck"];
            };
        };
        responses: {
            /** @description Successfully verified the recovery flow */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description The reset password flow was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    signout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    enable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enable TOTP response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnableResponse"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    enable_exchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnableExchange"];
            };
        };
        responses: {
            /** @description TOTP enabled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description The TOTP enable flow was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    exchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Exchange"];
            };
        };
        responses: {
            /** @description Successful TOTP exchange */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description The TOTP exchange flow was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    exchange_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Exchange"];
            };
        };
        responses: {
            /** @description Successful TOTP exchange */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description The TOTP exchange flow was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    funny: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description I'm a teapot :D */
            418: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    list_apps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of the user created OAuth apps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OauthApp"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    create_app: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApp"];
            };
        };
        responses: {
            /** @description OAuth app created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAppResponse"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    get_app: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the OAuth app to retrieve */
                id: components["schemas"]["StringId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OAuth app info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OauthApp"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description OAuth app not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    update_app: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the OAuth app to update */
                id: components["schemas"]["StringId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApp"];
            };
        };
        responses: {
            /** @description OAuth app updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description OAuth app not owned by the user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description OAuth app not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    delete_app: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the OAuth app to delete */
                id: components["schemas"]["StringId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth app deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description OAuth app not owned by the user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description OAuth app not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    list_authorized: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of the authorized OAuth apps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OauthAuthorized"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    get_authorized: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the authorized OAuth app to get */
                id: components["schemas"]["Ulid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authorized OAuth app info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OauthAuthorized"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Authorized OAuth app not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    remove_authorized: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the authorized OAuth app to delete */
                id: components["schemas"]["Ulid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully removed authorized OAuth app */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Authorized OAuth app not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    current_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Your current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    delete_all_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted all open sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    list_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of the your open sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the Session to get info about */
                id: components["schemas"]["Ulid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TinySession"][];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated or Sudo is not enabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    delete_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the Session to delete */
                id: components["schemas"]["Ulid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully deleted the session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated or Sudo is not enabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    get_sudo_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The available Sudo enable options */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentActiveOptions"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    enable_sudo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SudoEnableRequest"];
            };
        };
        responses: {
            /** @description Sudo has been enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SudoEnableResponse"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Sudo cannot be enabled with the chosen option */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Missing required fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    get_sudo_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current Sudo status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SudoStatus"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    disable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TOTP disabled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated or Sudo is not enabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    get_totp_recovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TOTP Recovery codes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpRecoveryResponse"];
                };
            };
            /** @description Validation or parsing error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
            /** @description Not authenticated or Sudo is not enabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpError"];
                };
            };
        };
    };
}
